baseURL: "https://leap2grow.github.io/"
languageCode: "en-us"
title: "Placeholder Project"
timezone: "UTC"
canonifyURLs: false
relativeURLs: false
enableRobotsTXT: true
disableKinds: ["section", "taxonomy", "term", "RSS", "sitemap"]
